// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: examples/models/orders.proto

package models

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Customer      string                 `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_examples_models_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_examples_models_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_examples_models_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

type OrderProcessed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProcessed) Reset() {
	*x = OrderProcessed{}
	mi := &file_examples_models_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProcessed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProcessed) ProtoMessage() {}

func (x *OrderProcessed) ProtoReflect() protoreflect.Message {
	mi := &file_examples_models_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProcessed.ProtoReflect.Descriptor instead.
func (*OrderProcessed) Descriptor() ([]byte, []int) {
	return file_examples_models_orders_proto_rawDescGZIP(), []int{1}
}

func (x *OrderProcessed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderProcessed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_examples_models_orders_proto protoreflect.FileDescriptor

const file_examples_models_orders_proto_rawDesc = "" +
	"\n" +
	"\x1cexamples/models/orders.proto\x12\x06models\"E\n" +
	"\fOrderCreated\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\"C\n" +
	"\x0eOrderProcessed\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB.Z,github.com/enercity/protoflow/examples/modelsb\x06proto3"

var (
	file_examples_models_orders_proto_rawDescOnce sync.Once
	file_examples_models_orders_proto_rawDescData []byte
)

func file_examples_models_orders_proto_rawDescGZIP() []byte {
	file_examples_models_orders_proto_rawDescOnce.Do(func() {
		file_examples_models_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_models_orders_proto_rawDesc), len(file_examples_models_orders_proto_rawDesc)))
	})
	return file_examples_models_orders_proto_rawDescData
}

var file_examples_models_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_models_orders_proto_goTypes = []any{
	(*OrderCreated)(nil),   // 0: models.OrderCreated
	(*OrderProcessed)(nil), // 1: models.OrderProcessed
}
var file_examples_models_orders_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_models_orders_proto_init() }
func file_examples_models_orders_proto_init() {
	if File_examples_models_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_models_orders_proto_rawDesc), len(file_examples_models_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_models_orders_proto_goTypes,
		DependencyIndexes: file_examples_models_orders_proto_depIdxs,
		MessageInfos:      file_examples_models_orders_proto_msgTypes,
	}.Build()
	File_examples_models_orders_proto = out.File
	file_examples_models_orders_proto_goTypes = nil
	file_examples_models_orders_proto_depIdxs = nil
}
